apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: pact-broker
  name: pact-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pact-broker
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: pact-broker
    spec:
      containers:
      - env:
        - name: PACT_BROKER_DATABASE_USERNAME
          value: postgres
        - name: PACT_BROKER_DATABASE_PASSWORD
          value: postgres
        - name: PACT_BROKER_DATABASE_HOST
          value: postgres
        - name: PACT_BROKER_DATABASE_NAME
          value: postgres
        - name: PACT_BROKER_PORT
          value: "9292"
        image: pactfoundation/pact-broker:2.72.0.3
        name: pact-broker
        ports:
        - containerPort: 9292
        resources: {}
      restartPolicy: Always
