apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: pact-broker
  name: pact-broker
spec:
  type: ClusterIP
  ports:
    - port: 9292
      targetPort: 9292
  selector:
    io.kompose.service: pact-broker
