apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 5432
    targetPort: 0
  selector:
    io.kompose.service: postgres